### ISSUE TITLE
Any way to get this into the CRAN repo?

### ISSUE THREAD

**Issue by csebranek** [luansheng/visPedigree#1]
Neat library.

I'm having some issues on my docker container using the method `install_github()`.

Would it be possible to get this package onto the CRAN repo? (https://cran.r-project.org/) so that the download method could be called using `install.packages()` ?

**Comment by luansheng** [comment]
Sorry, now this package is not uploaded on CRAN. I need more time to update this package.



Sheng Luan PhD
Yellow Sea Fisheries Research Institute, CAFS
106 Nanjing Road, Qingdao  266071
China
Tel： (0086) 13969749906
Email: luansheng@ysfri.ac.cn
 
From: Chad S.
Date: 2019-06-05 22:38
To: luansheng/visPedigree
CC: Subscribed
Subject: [luansheng/visPedigree] Any way to get this into the CRAN repo? (#1)
Neat library.
I'm having some issues on my docker container using the method install_github().
Would it be possible to get this package onto the CRAN repo? (https://cran.r-project.org/) so that the download method could be called using install.packages() ?

**Comment by csebranek** [comment]
Thanks.

Is there a timeline for when this could be added to CRAN?
